#!/bin/bash

# List of domains
domains=(
privacy.polywood.com
privacy.extremepizza.com
privacy.patriotgoldgroup.com
privacy.puracy.com
privacy.drhonow.com
privacy.zipfizz.com
privacy.skywatcherusa.com
privacy.careerkarma.com
privacy.crossfit.com
privacy.texasdebrazil.com
privacy.carcovers.com
privacy.cognitohq.com
privacy.martinellis.com
privacy.rawlings.com
privacy.clarev.com
privacy.amscope.co.uk
privacy.earthlite.com
privacy.redpocket.com
privacy.footwearetc.com
privacy.earthbreeze.co.uk
privacy.stagheaddesigns.com
privacy.jacksonschips.com
privacy.sportsresearch.com
privacy.triangl.com
privacy.feature.com
privacy.mipod.com
privacy.picturehangsolutions.com
privacy.lizardskins.com
privacy.rollerrabbit.com
privacy.dovitamins.com
privacy.diversdirect.com
privacy.thorne.com
privacy.exair.com
privacy.legendairymilk.com
privacy.chapterspot.com
privacy.baumbat.com
privacy.tazachocolate.com
privacy.medterra.com
privacy.nafnafgrill.com
privacy.fatandweirdcookie.com
privacy.reevul.com
privacy.madeincookware.com
privacy.marymacks.com
privacy.wrightsock.com
privacy.mindfulhealthlife.com
privacy.ringconcierge.com
privacy.tiege.com
privacy.maruccisports.com
privacy.guardianbikes.com
privacy.biglifejournal.com
privacy.orthofeet.com
privacy.beekeepersnaturals.com
privacy.cliffkeen.com
privacy.buildcover.com
privacy.selkiecollection.com
privacy.eatmezcla.com
privacy.jerrysartarama.com
privacy.convoso.com
privacy.eboost.com
privacy.parksproject.us
privacy.moscot.com
privacy.victussports.com
privacy.shoprhode.com
privacy.cozyearth.com
privacy.neurohacker.com
privacy.trymito.io
privacy.eatmush.com
privacy.essencemakeup.com
privacy.bachans.com
privacy.celestron.com
privacy.ostroy.com
privacy.wingzone.com
privacy.walnuts.org
privacy.realtyhop.com
privacy.geologie.com
privacy.lebarboutique.com
privacy.pranasleep.com
privacy.avocademy.com
privacy.shopdoen.com
privacy.vogmask.com
privacy.reynspooner.com
privacy.reuzel.com
privacy.umzu.com
privacy.nomatic.com
privacy.renthop.com
privacy.roccat.com
privacy.lumivyx.com
privacy.myteadrop.com
privacy.withjoy.com
privacy.gobros.com
privacy.rune.ai
privacy.famous-smoke.com
privacy.trihardus.com
privacy.acure.com
privacy.boylanbottling.com
privacy.18east.co
privacy.mudwtr.com
privacy.echonewyork.com
privacy.gregnormancollection.com
privacy.publicrec.com
privacy.madsportsstuff.com
privacy.citymattress.com
privacy.juno.bio
privacy.boka.com
privacy.prioritytire.com
privacy.houndsy.com
privacy.pairofthieves.com
privacy.budsies.com
privacy.rhinegeist.com
privacy.weezietowels.com
privacy.dadgrass.com
privacy.viori.com
privacy.toynk.com
privacy.fungi.com
privacy.satyajewelry.com
privacy.lawlessbeauty.com
privacy.tubbytodd.com
privacy.lorcoffee.com
privacy.vitalsleep.com
privacy.combatmfg.com
privacy.loudmouth.com
privacy.rishi-tea.com
privacy.idiggreenacres.com
privacy.sandcloud.com
privacy.vikingrevolution.com
privacy.nexusbrands.com
privacy.suntegrityskincare.com
privacy.roveconcepts.com
privacy.shopyourigami.com
privacy.naturalathleteclinic.com
privacy.daring.com
privacy.fewmoda.com
privacy.kandypens.com
privacy.wedderspoon.com
privacy.capriottis.com
privacy.givelegacy.com
privacy.alterecofoods.com
privacy.rhone.com
privacy.tortugarumcakes.com
privacy.keynutrients.com
privacy.sleepinnovations.com
privacy.capezio.com
privacy.anaono.com
privacy.californiababy.com
privacy.taosfootwear.com
privacy.unclejulios.com
privacy.kodiakcakes.com
privacy.unrealmobile.com
privacy.rsvpgallery.com
privacy.nickgraham.com
privacy.lesserevil.com
privacy.dartagnan.com
privacy.cafishgrill.com
privacy.thatsitfruit.com
privacy.eq3.com
privacy.nuebynovaform.com
privacy.iandloveandyou.com
privacy.bhfo.com
privacy.pax.com
privacy.amerisafe.com
privacy.puffy.com
privacy.kidpik.com
privacy.sundayriley.uk
privacy.futurhealth.com
privacy.stateandliberty.com
privacy.resourcefurniture.com
privacy.moonshinerods.com
privacy.zoskinhealth.com
privacy.promisebyeffy.com
privacy.thefinchcompany.org
privacy.annabeck.com
privacy.tommyjohn.com
privacy.californiainnovations.com
privacy.godwindirect.com
privacy.ymijeans.com
privacy.wildplanetfoods.com
privacy.kaged.com
privacy.palmettostatearmory.com
privacy.oka.com
privacy.lawrysonline.com
privacy.hibarhospitality.com
privacy.ericjavits.com
privacy.fabercastell.com
privacy.us.fotileglobal.com
privacy.novaformcomfort.com
privacy.fountsociety.com
privacy.nicksboots.com
privacy.soleprovisions.com
privacy.tumbleliving.com
privacy.frankiesbikinis.com
privacy.hensonshaving.com
privacy.neolife.com
privacy.smithey.com
privacy.incrediwear.com
privacy.lairdsuperfood.com
privacy.wellspringmeds.com
privacy.pery.com
privacy.philzcoffee.com
privacy.drinksupercoffee.com
privacy.konscious.us
privacy.solidcore.co
privacy.gmpc.com
privacy.huckberry.com
privacy.teatulia.com
privacy.weekday.works
privacy.iremedy.com
privacy.homelifemedia.com
privacy.nkhome.com
privacy.abbysonliving.com
privacy.portlandleathergoods.com
privacy.mugsyjeans.com
privacy.sparkleinpink.com
privacy.saltandstraw.com
privacy.mudpie.com
privacy.4knines.com
privacy.carlsgolfland.com
privacy.gesture.vip
privacy.epicsports.com
privacy.dogishuman.com
privacy.outrival.com
privacy.dunninggolf.com
privacy.swissklip.com
privacy.earthbreeze.com
privacy.zitsticka.co.uk
privacy.apothekary.co
privacy.jenniferbehr.com
privacy.jaquishbiomedical.com
privacy.mygeeni.com
privacy.runautomat.com
privacy.gourmetgiftbaskets.com
privacy.gallerydept.com
privacy.imageskincare.co.uk
privacy.popl.co
privacy.sevensundays.com
privacy.effyjewelry.com
privacy.ironflask.com
privacy.donpablocoffee.com
privacy.soflete.com
privacy.kimberamerica.com
privacy.topcoatproducts.com
privacy.naturehills.com
privacy.g-plans.com
privacy.royalbrush.com
privacy.lobstergram.com
privacy.teaforte.com
privacy.daniellefrankelstudio.com
privacy.skinnymixes.com
privacy.tiemart.com
privacy.safariland.com
privacy.innovativedining.com
privacy.zitsticka.com
privacy.brighton.com
privacy.genomelink.io
privacy.burrow.com
privacy.zbiotics.com
privacy.nutrabio.com
privacy.karmamobility.com
privacy.immieats.com
privacy.schleich-s.com
privacy.citizensofhumanity.com
privacy.myticktalk.com
privacy.azazie.com
privacy.goretailgroup.com
privacy.madeinnature.com
privacy.saltwater-sandals.com
privacy.truevault.com
privacy.rokform.com
privacy.toadandco.com
privacy.mypetsies.com
privacy.shopredone.com
privacy.sundayriley.com
privacy.summitgolfbrands.com
privacy.amscope.com
privacy.saiehello.com
privacy.ghostbed.com
privacy.farmerboys.com
privacy.gainful.com
privacy.gearaid.com
privacy.amawaterways.com
privacy.sydneyscloset.com
privacy.josiemaran.com
privacy.herrs.com
privacy.fireworks.com
privacy.ghostlifestyle.com
privacy.freshcap.com
privacy.hathaspace.com
privacy.solawave.co
privacy.theglutenfreebar.com
privacy.bajiosunglasses.com
privacy.artthatkills.com
privacy.catricecosmetics.com
privacy.beachbunnyswimwear.com
privacy.indielee.com
privacy.primallypure.com
privacy.simpalosnacks.com
privacy.swissklip.ca
privacy.shopduer.com
privacy.scholarsapp.com
privacy.vktry.com
privacy.trustedconsumersreviews.com
z20220829ecs.nanopolarbear.com
privacy.consuelastyle.com
privacy.onmolecule.com
privacy.assouline.com
privacy.obagi.com
privacy.stuffedanimalpros.com
privacy.pfcandleco.com
privacy.fancysprinkles.com
privacy.zquiet.com
privacy.baltini.com
privacy.fxi.com
privacy.freedompop.com
privacy.sportsbasement.com
privacy.fivecbd.com
privacy.venacbd.com
privacy.frownies.com
privacy.dtf.com
privacyrequest.imageskincare.com
privacy.safetyshoes.com
privacy.saatva.com
privacy.wtb.com
privacy.watchgang.com
privacy.theblacktux.com
privacy.ryonet.com
privacy.woodstream.com
privacy.spiceology.com
privacy.tacticalbabygear.com
privacy.robertscamera.com
privacy.ototodesign.com
privacy.heatholders.com
privacy.katburki.com
privacy.mightyvault.com
privacy.realstreetperformance.com
privacy.nutpods.com
privacy.fullstarkitchenware.com
privacy.thebshirt.clothing
privacy.ballwash.com
privacy.rockingreen.com
privacy.soma.truevaultstaging.com# Add the rest of your domains here...
)

# Authorization key
auth_key="Bearer my-privacy-center-builder-inbound-key"

# Base URL for the API
base_url="http://localhost:5000/api/privacycenter?url="

# Array to collect domains with optOutType "SHORT"
short_optout_domains=()

# Loop through each domain
for domain in "${domains[@]}"; do
  echo "Processing domain: $domain"

  # Make the HTTP GET request and extract only optOutFormOptions
  optOutFormOptions=$(http GET "${base_url}${domain}" Authorization:"$auth_key" | jq '.optOutFormOptions')

  # Print the optOutFormOptions
  echo "optOutFormOptions for $domain:"
  echo "$optOutFormOptions"
  echo

  # Check if optOutType is "SHORT" and add to the list
  optOutType=$(echo "$optOutFormOptions" | jq -r '.optOutType')
  if [ "$optOutType" == "SHORT" ]; then
    short_optout_domains+=("'$domain'") # Add quotes around domain
  fi
done

# Print SQL query
echo "---------------------------------------------"
echo "Generated SQL Query:"
echo "SELECT *"
echo "FROM privacy_centers"
echo "WHERE custom_domain IN ("
printf "    %s\n" "$(IFS=,; echo "${short_optout_domains[*]}")"
echo ");"
