- name: openai/claude-3.7-sonnet-thought
  edit_format: diff
  weak_model_name: github_copilot/claude-3.7-sonnet
  use_repo_map: true
  examples_as_sys_msg: true
  cache_control: true
  editor_model_name: github_copilot/claude-3.7-sonnet-thought
  editor_edit_format: editor-diff
  extra_params:
    max_tokens: 90000
    max_input_tokens: 128000
    max_output_tokens: 90000

- name: openai/gpt-4o
  extra_params:
    max_tokens: 8192

- name: openai/gemini-2.5-pro
  edit_format: diff-fenced
  use_repo_map: true
  extra_params:
    max_tokens: 128000
    max_input_tokens: 128000
    max_output_tokens: 128000

- name: openai/claude-sonnet-4
  extra_params:
    model: openai/claude-sonnet-4
