dark-mode: true
auto-commits: false
editor: nvim
map-tokens: 2048
code-theme: nord-darker
analytics: false
show-model-warnings: false
auto-commits: false
cache-prompts: true
openai-api-base: https://api.githubcopilot.com
model: openai/gpt-4o
weak-model: openai/gpt-4o-mini
show-model-warnings: false
max-chat-history-tokens: 8000
upgrade: false
auto-accept-architect: false
alias:
  - "fast:openai/gpt-4o"
  - "code:openai/claude-3.7-sonnet"
  - "think:openai/claude-3.7-sonnet-thought"
  - "gemini:openai/gemini-2.5-pro"

## Get the Copilot API Key using a Jetbrains product it dropps it in
# CONFIG_PATH="${HOME}/.config/github-copilot/apps.json"


