#!/usr/bin/env bash

SYSTEM_TYPE=$(uname -s)
COMPUTER_NAME="truevaultpolarbear"

#-----------------------------------------
# * Install Homebrew
# * Install brew packages
#   https://yadm.io/docs/bootstrap
#-----------------------------------------

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

if [ "$SYSTEM_TYPE" = "Darwin" ]; then

  if ! command -v mas >/dev/null 2>&1; then
    echo ">>> Wipe all default doc icons.."
    defaults write com.apple.dock persistent-apps -array ""

    find "${HOME}/Library/Application Support/Dock" -name "*-*.db" -maxdepth 1 -delete

    echo ">>> Installing mas.."
    brew install mas
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo ">>> Installing brew packages.."
    brew bundle --global -v
  fi
fi

# Install Node JS
echo "Node JS Install"
fnm install --lts

# Setup Java
echo "Setting up JDK Symlink"
sudo ln -sfn /opt/homebrew/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk

# Name Computer
sudo scutil --set ComputerName "$COMPUTER_NAME"
sudo scutil --set HostName "$COMPUTER_NAME"
sudo scutil --set LocalHostName "$COMPUTER_NAME"

# SSD
echo "Disable local Time Machine snapshots"
sudo tmutil disable local

# Mouse
echo "Super Fast Mouse Speed"
defaults write NSGlobalDomain com.apple.mouse.scaling -int 3

echo "Super Fast Trackpad Speed"
defaults write NSGlobalDomain com.apple.trackpad.scaling -int 3

echo "Tap to click"
defaults write com.apple.AppleMultitouchTrackpad Clicking -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -int 1

echo "3 Finger Drag"
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerDrag -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerHorizSwipeGesture -int 0
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerVertSwipeGesture -int 0
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerDrag -int 1
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerHorizSwipeGesture -int 0
defaults write com.apple.AppleMultitouchTrackpad TrackpadThreeFingerVertSwipeGesture -int 0

echo "Disable shaking to locate"
defaults write NSGlobalDomain CGDisableCursorLocationMagnification -bool true

echo "Disable the Launchpad gesture (pinch with thumb and three fingers)"
defaults write com.apple.dock showLaunchpadGestureEnabled -int 0

# UI
echo "Show menu bar"
defaults write NSGlobalDomain _HIHideMenuBar -bool false

echo "Autohide dock"
defaults write com.apple.WindowManager AutoHide -int 0

# Keyboard
echo "Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)"
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

echo "Disable press-and-hold for keys in favor of key repeat"
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

echo "Set a blazingly fast keyboard repeat rate"
defaults write NSGlobalDomain KeyRepeat -int 2 # 60 default, 1 was too fast
defaults write NSGlobalDomain InitialKeyRepeat -int 35 # 68 default, 10 was too fast

echo "Disable auto-correct"
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Dock and Dashboard
echo "Set the icon size of Dock items to 35 pixels"
defaults write com.apple.dock tilesize -int 35

echo "Set dock to left side of screen"
defaults write com.apple.dock orientation -string "right"

# Screen
echo "Require password immediately after sleep or screen saver begins"
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

echo "Save screenshots in PNG format (other options: BMP, GIF, JPG, PDF, TIFF)"
defaults write com.apple.screencapture type -string "png"

echo "Disable shadow in screenshots"
defaults write com.apple.screencapture disable-shadow -bool true

# Bluetooth
echo "Enable AAC and APTx"
sudo defaults write bluetoothaudiod "Enable AptX codec" -bool true
sudo defaults write bluetoothaudiod "Enable AAC codec" -bool true
sudo defaults write bluetoothaudiod "AAC Bitrate" 320

# Finder
echo "Hide all desktop icons"
defaults write com.apple.finder CreateDesktop false

echo "Show hidden files by default"
defaults write com.apple.finder AppleShowAllFiles -bool true

echo "Show all filename extensions"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

echo "Show status bar"
defaults write com.apple.finder ShowStatusBar -bool true

echo "Show path bar"
defaults write com.apple.finder ShowPathbar -bool true

echo "Display full POSIX path as Finder window title"
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true

echo "When performing a search, search the current folder by default"
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

echo "Disable the warning when changing a file extension"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

echo "Remove the spring loading delay for directories"
defaults write NSGlobalDomain com.apple.springing.delay -float 0

echo "Avoid creating .DS_Store files on network volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

echo "Use list view in all Finder windows by default"
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"

echo "Disable the warning before emptying the Trash"
defaults write com.apple.finder WarnOnEmptyTrash -bool false

echo "Empty Trash securely by default"
defaults write com.apple.finder EmptyTrashSecurely -bool true

echo "Show the ~/Library folder"
chflags nohidden ~/Library

# Dock
echo "Minimize windows into their application’s icon"
defaults write com.apple.dock minimize-to-application -bool true
#
# echo "Don't show recents in the doc"
# defaults write com.apple.dock show-recents -bool false
#
# echo "Show indicator lights for open applications in the Dock"
# defaults write com.apple.dock show-process-indicators -bool true
#
# echo "Don’t animate opening applications from the Dock"
# defaults write com.apple.dock launchanim -bool false
#
# echo "Speed up Mission Control animations"
# defaults write com.apple.dock expose-animation-duration -float 0.1
#
# echo "Disable Dashboard"
# defaults write com.apple.dashboard mcx-disabled -bool true
#
# echo "Don’t show Dashboard as a Space"
# defaults write com.apple.dock dashboard-in-overlay -bool true
#
# echo "Remove the auto-hiding Dock delay"
# defaults write com.apple.dock autohide-delay -float 0
#
# echo "Remove the animation when hiding/showing the Dock"
# defaults write com.apple.dock autohide-time-modifier -float 0
#
# echo "Automatically hide and show the Dock"
# defaults write com.apple.dock autohide -bool true
#
# echo "Make Dock icons of hidden applications translucent"
# defaults write com.apple.dock showhidden -bool true
#
# echo "Make Dock more transparent"
# defaults write com.apple.dock hide-mirror -bool true


# TODO Not sure if we need these??
# echo "double click maximize"
# defaults write NSGlobalDomain AppleActionOnDoubleClick -string "Maximize"
#
# echo "Increase window resize speed for Cocoa applications"
# defaults write NSGlobalDomain NSWindowResizeTime -float 0.001
#
# echo "Expand save panel by default"
# defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
# defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
#
# echo "Expand print panel by default"
# defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
# defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true
#
# echo "Automatically quit printer app once the print jobs complete"
# defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true
#
# echo "Disable the Are you sure you want to open this application dialog"
# defaults write com.apple.LaunchServices LSQuarantine -bool false
#
# echo "Disable the crash reporter"
# defaults write com.apple.CrashReporter DialogType -string "none"
#
# echo "Disable smart quotes as they’re annoying when typing code"
# defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
#
# echo "Disable smart dashes as they’re annoying when typing code"
# defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# echo "Disable menu sounds"
# defaults write NSGlobalDomain com.apple.sound.uiaudio.enabled -bool false

# Screen
# echo "Enable subpixel font rendering on non-Apple LCDs"
# defaults write NSGlobalDomain AppleFontSmoothing -int 2
#
# echo "Enable HiDPI display modes (requires restart)"
# sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true

# echo "Allow quitting via ⌘ + Q;"
# defaults write com.apple.finder QuitMenuItem -bool true

# echo "Disable window animations and Get Info animations"
# defaults write com.apple.finder DisableAllAnimations -bool true

# echo "Disable disk image verification"
# defaults write com.apple.frameworks.diskimages skip-verify -bool true
# defaults write com.apple.frameworks.diskimages skip-verify-locked -bool true
# defaults write com.apple.frameworks.diskimages skip-verify-remote -bool true

# echo "Automatically open a new Finder window when a volume is mounted"
# defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
# defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
# defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
